twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  globals:
    meta_title: 'Test Task List'

  paths:
    '%kernel.project_dir%/templates': Templates